### ISSUE TITLE
don't run `startup.jl` when using `ion`

### ISSUE THREAD

**Issue by johnnychen94** [Roger-luo/IonCLI.jl#26]
I have included `Revise`, `OhMyREPL`, and others in my `startup.jl`, it turns out that this makes using `ion` quite laggy.

I'm not sure if there's a way to skip this, but for the purpose of `ion`, it doesn't need to include `startup.jl`.

**Comment by Roger-luo** [comment]
yeah, this make sense, this should be generated in https://github.com/Roger-luo/Comonicon.jl/blob/master/src/tools/build.jl#L417

**Comment by Roger-luo** [comment]
should be resolved in v0.4.7, please try it again when https://github.com/JuliaRegistries/General/pull/20192 gets tagged.

**Comment by Roger-luo** [comment]
does this work for you now? @johnnychen94

**Comment by johnnychen94** [comment]
Yeah, this works now. Thanks for doing this!

Another issue is that it fails to find the available sysimage artifact at the build stage, I've opened a PR #29 to set a fallback in this case.
